apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 100
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: simple-express-app
        image: gokeobasa/simple-express-app
        ports:
        - name: nodejs-port
          containerPort: 3000



